redirect_uris = "http://localhost:8501/"
testing_mode = true
client_id = '122617795125-b7dqa5o4jfpbs01k00brfgku1kpbd7s4.apps.googleusercontent.com'
client_secret = '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'
redirect_url_test = 'http://localhost:8501/'
redirect_url = "subchef.mrdavisdev.com"

[mongo]
uri = "mongodb://mongo:QzZiVjlYpPrPHnZEyZYllJoJBrZBtZAx@monorail.proxy.rlwy.net:45904"

[gemini]
api_key = "AIzaSyBiaYnuefOuRKJk5KxQSR_KFxMi7Ks-w4w"
