redirect_uris = "${REDIRECT_URIS}"
testing_mode = false
client_id = '${CLIENT_ID}'
client_secret = '${CLIENT_SECRET}'
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://subchef.mrdavisdev.com/"

[mongo]
uri = "${MONGO_URI}"

[gemini]
api_key = "${GEMINI_API_KEY}"